import type { OrderRow } from "./types";

export const ordersData: OrderRow[] = [
  {
    id: "ORD-1023",
    orderId: "ORD-1023",
    customerId: "CUS-301",
    customerNickName: "Maya",
    orderType: "Brova",
    mobileNumber: "+91 98765 43210",
    remainingPayment: 12500,
    promisedDeliveryDate: "2024-10-22",
    receivedAtShowroom: "2024-10-18",
    delayInDays: 0,
    quantity: 4,
    r1: {
      date: "2024-09-01",
      note: "Initial follow-up completed. Measurements confirmed at the showroom.",
    },
    r2: {
      date: "2024-09-15",
      note: "Fabric availability confirmed with vendor. Awaiting trims from supplier.",
    },
    callReminders: [
      {
        id: "ORD-1023-call-1",
        date: "2024-10-12",
        connected: true,
        note: "Customer confirmed readiness for pickup on weekend.",
      },
    ],
    escalation: { status: "None" },
  },
  {
    id: "ORD-1044",
    orderId: "ORD-1044",
    customerId: "CUS-327",
    customerNickName: "Ravi",
    orderType: "Final",
    mobileNumber: "+91 99876 54321",
    remainingPayment: 28500,
    promisedDeliveryDate: "2024-10-18",
    receivedAtShowroom: "2024-10-17",
    delayInDays: 1,
    quantity: 2,
    r1: {
      date: "2024-09-05",
      note: "Shared swatch photos and confirmed colour preference over call.",
    },
    r2: {
      date: "2024-09-28",
      note: "Explained stitching delay because of festive rush; customer acknowledged.",
    },
    r3: {
      date: "2024-10-10",
      note: "Third reminder sent with revised promised date.",
    },
    callReminders: [
      {
        id: "ORD-1044-call-1",
        date: "2024-10-14",
        connected: false,
        note: "Left voicemail requesting confirmation of pickup slot.",
      },
      {
        id: "ORD-1044-call-2",
        date: "2024-10-16",
        connected: true,
        note: "Customer confirmed arrival on 17 Oct evening.",
      },
    ],
    escalation: {
      status: "Escalated",
      date: "2024-10-11",
    },
  },
  {
    id: "ORD-1052",
    orderId: "ORD-1052",
    customerId: "CUS-346",
    customerNickName: "Sarah",
    orderType: "Alteration",
    mobileNumber: "+91 91234 56780",
    remainingPayment: 7200,
    promisedDeliveryDate: "2024-10-25",
    delayInDays: 0,
    quantity: 6,
    callReminders: [],
    escalation: { status: "None" },
  },
  {
    id: "ORD-1070",
    orderId: "ORD-1070",
    customerId: "CUS-359",
    customerNickName: "Imran",
    orderType: "Brova",
    mobileNumber: "+91 93450 87654",
    remainingPayment: 0,
    promisedDeliveryDate: "2024-10-12",
    receivedAtShowroom: "2024-10-09",
    delayInDays: 0,
    quantity: 3,
    r1: {
      date: "2024-09-02",
      note: "Recorded that the customer paid advance in-store.",
    },
    callReminders: [
      {
        id: "ORD-1070-call-1",
        date: "2024-10-05",
        connected: true,
        note: "Asked to inspect panels before final polishing; customer visited same day.",
      },
    ],
    escalation: { status: "None" },
  },
  {
    id: "ORD-1081",
    orderId: "ORD-1081",
    customerId: "CUS-402",
    customerNickName: "Lina",
    orderType: "Final",
    mobileNumber: "+91 97654 12345",
    remainingPayment: 18450,
    promisedDeliveryDate: "2024-10-05",
    delayInDays: 5,
    quantity: 1,
    r1: {
      date: "2024-08-28",
      note: "Confirmed fabric change requested by customer.",
    },
    r2: {
      date: "2024-09-12",
      note: "Technician visit scheduled for onsite fitting confirmation.",
    },
    callReminders: [
      {
        id: "ORD-1081-call-1",
        date: "2024-10-03",
        connected: false,
        note: "Call dropped; sent SMS with revised delivery date.",
      },
    ],
    escalation: {
      status: "Escalated",
      date: "2024-10-08",
    },
  },
];
