/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AboutRouteImport } from './routes/about'
import { Route as MainRouteRouteImport } from './routes/$main/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainIndexRouteImport } from './routes/$main/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as MainStoreStockReportRouteImport } from './routes/$main/store/stock-report'
import { Route as MainStoreRequestDeliveryRouteImport } from './routes/$main/store/request-delivery'
import { Route as MainStoreReceivingDeliveriesRouteImport } from './routes/$main/store/receiving-deliveries'
import { Route as MainStoreEndOfDayReportRouteImport } from './routes/$main/store/end-of-day-report'
import { Route as MainOrdersOrdersAtShowroomRouteImport } from './routes/$main/orders/orders-at-showroom'
import { Route as MainOrdersNewWorkOrderRouteImport } from './routes/$main/orders/new-work-order'
import { Route as MainOrdersNewSalesOrderRouteImport } from './routes/$main/orders/new-sales-order'
import { Route as MainOrdersNewAlterationOrderRouteImport } from './routes/$main/orders/new-alteration-order'
import { Route as MainOrdersCustomerProfilesOrdersRouteImport } from './routes/$main/orders/customer-profiles-orders'
import { Route as MainOrdersOrderManagementUnlinkRouteImport } from './routes/$main/orders/order-management/unlink'
import { Route as MainOrdersOrderManagementReceivingBrovaFinalRouteImport } from './routes/$main/orders/order-management/receiving-brova-final'
import { Route as MainOrdersOrderManagementLinkRouteImport } from './routes/$main/orders/order-management/link'
import { Route as MainOrdersOrderManagementFinalFeedbackRouteImport } from './routes/$main/orders/order-management/final-feedback'
import { Route as MainOrdersOrderManagementDispatchRouteImport } from './routes/$main/orders/order-management/dispatch'
import { Route as MainOrdersOrderManagementChangeOptionsRouteImport } from './routes/$main/orders/order-management/change-options'
import { Route as MainOrdersOrderManagementCancelOrderRouteImport } from './routes/$main/orders/order-management/cancel-order'
import { Route as MainOrdersOrderManagementBrovaFeedbackRouteImport } from './routes/$main/orders/order-management/brova-feedback'
import { Route as MainOrdersOrderManagementAlterationsRouteImport } from './routes/$main/orders/order-management/alterations'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/$main',
  path: '/$main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainStoreStockReportRoute = MainStoreStockReportRouteImport.update({
  id: '/store/stock-report',
  path: '/store/stock-report',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainStoreRequestDeliveryRoute =
  MainStoreRequestDeliveryRouteImport.update({
    id: '/store/request-delivery',
    path: '/store/request-delivery',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainStoreReceivingDeliveriesRoute =
  MainStoreReceivingDeliveriesRouteImport.update({
    id: '/store/receiving-deliveries',
    path: '/store/receiving-deliveries',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainStoreEndOfDayReportRoute = MainStoreEndOfDayReportRouteImport.update({
  id: '/store/end-of-day-report',
  path: '/store/end-of-day-report',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainOrdersOrdersAtShowroomRoute =
  MainOrdersOrdersAtShowroomRouteImport.update({
    id: '/orders/orders-at-showroom',
    path: '/orders/orders-at-showroom',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersNewWorkOrderRoute = MainOrdersNewWorkOrderRouteImport.update({
  id: '/orders/new-work-order',
  path: '/orders/new-work-order',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainOrdersNewSalesOrderRoute = MainOrdersNewSalesOrderRouteImport.update({
  id: '/orders/new-sales-order',
  path: '/orders/new-sales-order',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainOrdersNewAlterationOrderRoute =
  MainOrdersNewAlterationOrderRouteImport.update({
    id: '/orders/new-alteration-order',
    path: '/orders/new-alteration-order',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersCustomerProfilesOrdersRoute =
  MainOrdersCustomerProfilesOrdersRouteImport.update({
    id: '/orders/customer-profiles-orders',
    path: '/orders/customer-profiles-orders',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersOrderManagementUnlinkRoute =
  MainOrdersOrderManagementUnlinkRouteImport.update({
    id: '/orders/order-management/unlink',
    path: '/orders/order-management/unlink',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersOrderManagementReceivingBrovaFinalRoute =
  MainOrdersOrderManagementReceivingBrovaFinalRouteImport.update({
    id: '/orders/order-management/receiving-brova-final',
    path: '/orders/order-management/receiving-brova-final',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersOrderManagementLinkRoute =
  MainOrdersOrderManagementLinkRouteImport.update({
    id: '/orders/order-management/link',
    path: '/orders/order-management/link',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersOrderManagementFinalFeedbackRoute =
  MainOrdersOrderManagementFinalFeedbackRouteImport.update({
    id: '/orders/order-management/final-feedback',
    path: '/orders/order-management/final-feedback',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersOrderManagementDispatchRoute =
  MainOrdersOrderManagementDispatchRouteImport.update({
    id: '/orders/order-management/dispatch',
    path: '/orders/order-management/dispatch',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersOrderManagementChangeOptionsRoute =
  MainOrdersOrderManagementChangeOptionsRouteImport.update({
    id: '/orders/order-management/change-options',
    path: '/orders/order-management/change-options',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersOrderManagementCancelOrderRoute =
  MainOrdersOrderManagementCancelOrderRouteImport.update({
    id: '/orders/order-management/cancel-order',
    path: '/orders/order-management/cancel-order',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersOrderManagementBrovaFeedbackRoute =
  MainOrdersOrderManagementBrovaFeedbackRouteImport.update({
    id: '/orders/order-management/brova-feedback',
    path: '/orders/order-management/brova-feedback',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersOrderManagementAlterationsRoute =
  MainOrdersOrderManagementAlterationsRouteImport.update({
    id: '/orders/order-management/alterations',
    path: '/orders/order-management/alterations',
    getParentRoute: () => MainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$main': typeof MainRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/home': typeof HomeRoute
  '/login': typeof authLoginRoute
  '/$main/': typeof MainIndexRoute
  '/$main/orders/customer-profiles-orders': typeof MainOrdersCustomerProfilesOrdersRoute
  '/$main/orders/new-alteration-order': typeof MainOrdersNewAlterationOrderRoute
  '/$main/orders/new-sales-order': typeof MainOrdersNewSalesOrderRoute
  '/$main/orders/new-work-order': typeof MainOrdersNewWorkOrderRoute
  '/$main/orders/orders-at-showroom': typeof MainOrdersOrdersAtShowroomRoute
  '/$main/store/end-of-day-report': typeof MainStoreEndOfDayReportRoute
  '/$main/store/receiving-deliveries': typeof MainStoreReceivingDeliveriesRoute
  '/$main/store/request-delivery': typeof MainStoreRequestDeliveryRoute
  '/$main/store/stock-report': typeof MainStoreStockReportRoute
  '/$main/orders/order-management/alterations': typeof MainOrdersOrderManagementAlterationsRoute
  '/$main/orders/order-management/brova-feedback': typeof MainOrdersOrderManagementBrovaFeedbackRoute
  '/$main/orders/order-management/cancel-order': typeof MainOrdersOrderManagementCancelOrderRoute
  '/$main/orders/order-management/change-options': typeof MainOrdersOrderManagementChangeOptionsRoute
  '/$main/orders/order-management/dispatch': typeof MainOrdersOrderManagementDispatchRoute
  '/$main/orders/order-management/final-feedback': typeof MainOrdersOrderManagementFinalFeedbackRoute
  '/$main/orders/order-management/link': typeof MainOrdersOrderManagementLinkRoute
  '/$main/orders/order-management/receiving-brova-final': typeof MainOrdersOrderManagementReceivingBrovaFinalRoute
  '/$main/orders/order-management/unlink': typeof MainOrdersOrderManagementUnlinkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/home': typeof HomeRoute
  '/login': typeof authLoginRoute
  '/$main': typeof MainIndexRoute
  '/$main/orders/customer-profiles-orders': typeof MainOrdersCustomerProfilesOrdersRoute
  '/$main/orders/new-alteration-order': typeof MainOrdersNewAlterationOrderRoute
  '/$main/orders/new-sales-order': typeof MainOrdersNewSalesOrderRoute
  '/$main/orders/new-work-order': typeof MainOrdersNewWorkOrderRoute
  '/$main/orders/orders-at-showroom': typeof MainOrdersOrdersAtShowroomRoute
  '/$main/store/end-of-day-report': typeof MainStoreEndOfDayReportRoute
  '/$main/store/receiving-deliveries': typeof MainStoreReceivingDeliveriesRoute
  '/$main/store/request-delivery': typeof MainStoreRequestDeliveryRoute
  '/$main/store/stock-report': typeof MainStoreStockReportRoute
  '/$main/orders/order-management/alterations': typeof MainOrdersOrderManagementAlterationsRoute
  '/$main/orders/order-management/brova-feedback': typeof MainOrdersOrderManagementBrovaFeedbackRoute
  '/$main/orders/order-management/cancel-order': typeof MainOrdersOrderManagementCancelOrderRoute
  '/$main/orders/order-management/change-options': typeof MainOrdersOrderManagementChangeOptionsRoute
  '/$main/orders/order-management/dispatch': typeof MainOrdersOrderManagementDispatchRoute
  '/$main/orders/order-management/final-feedback': typeof MainOrdersOrderManagementFinalFeedbackRoute
  '/$main/orders/order-management/link': typeof MainOrdersOrderManagementLinkRoute
  '/$main/orders/order-management/receiving-brova-final': typeof MainOrdersOrderManagementReceivingBrovaFinalRoute
  '/$main/orders/order-management/unlink': typeof MainOrdersOrderManagementUnlinkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$main': typeof MainRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/home': typeof HomeRoute
  '/(auth)/login': typeof authLoginRoute
  '/$main/': typeof MainIndexRoute
  '/$main/orders/customer-profiles-orders': typeof MainOrdersCustomerProfilesOrdersRoute
  '/$main/orders/new-alteration-order': typeof MainOrdersNewAlterationOrderRoute
  '/$main/orders/new-sales-order': typeof MainOrdersNewSalesOrderRoute
  '/$main/orders/new-work-order': typeof MainOrdersNewWorkOrderRoute
  '/$main/orders/orders-at-showroom': typeof MainOrdersOrdersAtShowroomRoute
  '/$main/store/end-of-day-report': typeof MainStoreEndOfDayReportRoute
  '/$main/store/receiving-deliveries': typeof MainStoreReceivingDeliveriesRoute
  '/$main/store/request-delivery': typeof MainStoreRequestDeliveryRoute
  '/$main/store/stock-report': typeof MainStoreStockReportRoute
  '/$main/orders/order-management/alterations': typeof MainOrdersOrderManagementAlterationsRoute
  '/$main/orders/order-management/brova-feedback': typeof MainOrdersOrderManagementBrovaFeedbackRoute
  '/$main/orders/order-management/cancel-order': typeof MainOrdersOrderManagementCancelOrderRoute
  '/$main/orders/order-management/change-options': typeof MainOrdersOrderManagementChangeOptionsRoute
  '/$main/orders/order-management/dispatch': typeof MainOrdersOrderManagementDispatchRoute
  '/$main/orders/order-management/final-feedback': typeof MainOrdersOrderManagementFinalFeedbackRoute
  '/$main/orders/order-management/link': typeof MainOrdersOrderManagementLinkRoute
  '/$main/orders/order-management/receiving-brova-final': typeof MainOrdersOrderManagementReceivingBrovaFinalRoute
  '/$main/orders/order-management/unlink': typeof MainOrdersOrderManagementUnlinkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$main'
    | '/about'
    | '/home'
    | '/login'
    | '/$main/'
    | '/$main/orders/customer-profiles-orders'
    | '/$main/orders/new-alteration-order'
    | '/$main/orders/new-sales-order'
    | '/$main/orders/new-work-order'
    | '/$main/orders/orders-at-showroom'
    | '/$main/store/end-of-day-report'
    | '/$main/store/receiving-deliveries'
    | '/$main/store/request-delivery'
    | '/$main/store/stock-report'
    | '/$main/orders/order-management/alterations'
    | '/$main/orders/order-management/brova-feedback'
    | '/$main/orders/order-management/cancel-order'
    | '/$main/orders/order-management/change-options'
    | '/$main/orders/order-management/dispatch'
    | '/$main/orders/order-management/final-feedback'
    | '/$main/orders/order-management/link'
    | '/$main/orders/order-management/receiving-brova-final'
    | '/$main/orders/order-management/unlink'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/home'
    | '/login'
    | '/$main'
    | '/$main/orders/customer-profiles-orders'
    | '/$main/orders/new-alteration-order'
    | '/$main/orders/new-sales-order'
    | '/$main/orders/new-work-order'
    | '/$main/orders/orders-at-showroom'
    | '/$main/store/end-of-day-report'
    | '/$main/store/receiving-deliveries'
    | '/$main/store/request-delivery'
    | '/$main/store/stock-report'
    | '/$main/orders/order-management/alterations'
    | '/$main/orders/order-management/brova-feedback'
    | '/$main/orders/order-management/cancel-order'
    | '/$main/orders/order-management/change-options'
    | '/$main/orders/order-management/dispatch'
    | '/$main/orders/order-management/final-feedback'
    | '/$main/orders/order-management/link'
    | '/$main/orders/order-management/receiving-brova-final'
    | '/$main/orders/order-management/unlink'
  id:
    | '__root__'
    | '/'
    | '/$main'
    | '/about'
    | '/home'
    | '/(auth)/login'
    | '/$main/'
    | '/$main/orders/customer-profiles-orders'
    | '/$main/orders/new-alteration-order'
    | '/$main/orders/new-sales-order'
    | '/$main/orders/new-work-order'
    | '/$main/orders/orders-at-showroom'
    | '/$main/store/end-of-day-report'
    | '/$main/store/receiving-deliveries'
    | '/$main/store/request-delivery'
    | '/$main/store/stock-report'
    | '/$main/orders/order-management/alterations'
    | '/$main/orders/order-management/brova-feedback'
    | '/$main/orders/order-management/cancel-order'
    | '/$main/orders/order-management/change-options'
    | '/$main/orders/order-management/dispatch'
    | '/$main/orders/order-management/final-feedback'
    | '/$main/orders/order-management/link'
    | '/$main/orders/order-management/receiving-brova-final'
    | '/$main/orders/order-management/unlink'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  HomeRoute: typeof HomeRoute
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$main': {
      id: '/$main'
      path: '/$main'
      fullPath: '/$main'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$main/': {
      id: '/$main/'
      path: '/'
      fullPath: '/$main/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$main/store/stock-report': {
      id: '/$main/store/stock-report'
      path: '/store/stock-report'
      fullPath: '/$main/store/stock-report'
      preLoaderRoute: typeof MainStoreStockReportRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/store/request-delivery': {
      id: '/$main/store/request-delivery'
      path: '/store/request-delivery'
      fullPath: '/$main/store/request-delivery'
      preLoaderRoute: typeof MainStoreRequestDeliveryRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/store/receiving-deliveries': {
      id: '/$main/store/receiving-deliveries'
      path: '/store/receiving-deliveries'
      fullPath: '/$main/store/receiving-deliveries'
      preLoaderRoute: typeof MainStoreReceivingDeliveriesRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/store/end-of-day-report': {
      id: '/$main/store/end-of-day-report'
      path: '/store/end-of-day-report'
      fullPath: '/$main/store/end-of-day-report'
      preLoaderRoute: typeof MainStoreEndOfDayReportRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/orders-at-showroom': {
      id: '/$main/orders/orders-at-showroom'
      path: '/orders/orders-at-showroom'
      fullPath: '/$main/orders/orders-at-showroom'
      preLoaderRoute: typeof MainOrdersOrdersAtShowroomRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/new-work-order': {
      id: '/$main/orders/new-work-order'
      path: '/orders/new-work-order'
      fullPath: '/$main/orders/new-work-order'
      preLoaderRoute: typeof MainOrdersNewWorkOrderRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/new-sales-order': {
      id: '/$main/orders/new-sales-order'
      path: '/orders/new-sales-order'
      fullPath: '/$main/orders/new-sales-order'
      preLoaderRoute: typeof MainOrdersNewSalesOrderRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/new-alteration-order': {
      id: '/$main/orders/new-alteration-order'
      path: '/orders/new-alteration-order'
      fullPath: '/$main/orders/new-alteration-order'
      preLoaderRoute: typeof MainOrdersNewAlterationOrderRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/customer-profiles-orders': {
      id: '/$main/orders/customer-profiles-orders'
      path: '/orders/customer-profiles-orders'
      fullPath: '/$main/orders/customer-profiles-orders'
      preLoaderRoute: typeof MainOrdersCustomerProfilesOrdersRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/order-management/unlink': {
      id: '/$main/orders/order-management/unlink'
      path: '/orders/order-management/unlink'
      fullPath: '/$main/orders/order-management/unlink'
      preLoaderRoute: typeof MainOrdersOrderManagementUnlinkRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/order-management/receiving-brova-final': {
      id: '/$main/orders/order-management/receiving-brova-final'
      path: '/orders/order-management/receiving-brova-final'
      fullPath: '/$main/orders/order-management/receiving-brova-final'
      preLoaderRoute: typeof MainOrdersOrderManagementReceivingBrovaFinalRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/order-management/link': {
      id: '/$main/orders/order-management/link'
      path: '/orders/order-management/link'
      fullPath: '/$main/orders/order-management/link'
      preLoaderRoute: typeof MainOrdersOrderManagementLinkRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/order-management/final-feedback': {
      id: '/$main/orders/order-management/final-feedback'
      path: '/orders/order-management/final-feedback'
      fullPath: '/$main/orders/order-management/final-feedback'
      preLoaderRoute: typeof MainOrdersOrderManagementFinalFeedbackRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/order-management/dispatch': {
      id: '/$main/orders/order-management/dispatch'
      path: '/orders/order-management/dispatch'
      fullPath: '/$main/orders/order-management/dispatch'
      preLoaderRoute: typeof MainOrdersOrderManagementDispatchRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/order-management/change-options': {
      id: '/$main/orders/order-management/change-options'
      path: '/orders/order-management/change-options'
      fullPath: '/$main/orders/order-management/change-options'
      preLoaderRoute: typeof MainOrdersOrderManagementChangeOptionsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/order-management/cancel-order': {
      id: '/$main/orders/order-management/cancel-order'
      path: '/orders/order-management/cancel-order'
      fullPath: '/$main/orders/order-management/cancel-order'
      preLoaderRoute: typeof MainOrdersOrderManagementCancelOrderRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/order-management/brova-feedback': {
      id: '/$main/orders/order-management/brova-feedback'
      path: '/orders/order-management/brova-feedback'
      fullPath: '/$main/orders/order-management/brova-feedback'
      preLoaderRoute: typeof MainOrdersOrderManagementBrovaFeedbackRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/order-management/alterations': {
      id: '/$main/orders/order-management/alterations'
      path: '/orders/order-management/alterations'
      fullPath: '/$main/orders/order-management/alterations'
      preLoaderRoute: typeof MainOrdersOrderManagementAlterationsRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainOrdersCustomerProfilesOrdersRoute: typeof MainOrdersCustomerProfilesOrdersRoute
  MainOrdersNewAlterationOrderRoute: typeof MainOrdersNewAlterationOrderRoute
  MainOrdersNewSalesOrderRoute: typeof MainOrdersNewSalesOrderRoute
  MainOrdersNewWorkOrderRoute: typeof MainOrdersNewWorkOrderRoute
  MainOrdersOrdersAtShowroomRoute: typeof MainOrdersOrdersAtShowroomRoute
  MainStoreEndOfDayReportRoute: typeof MainStoreEndOfDayReportRoute
  MainStoreReceivingDeliveriesRoute: typeof MainStoreReceivingDeliveriesRoute
  MainStoreRequestDeliveryRoute: typeof MainStoreRequestDeliveryRoute
  MainStoreStockReportRoute: typeof MainStoreStockReportRoute
  MainOrdersOrderManagementAlterationsRoute: typeof MainOrdersOrderManagementAlterationsRoute
  MainOrdersOrderManagementBrovaFeedbackRoute: typeof MainOrdersOrderManagementBrovaFeedbackRoute
  MainOrdersOrderManagementCancelOrderRoute: typeof MainOrdersOrderManagementCancelOrderRoute
  MainOrdersOrderManagementChangeOptionsRoute: typeof MainOrdersOrderManagementChangeOptionsRoute
  MainOrdersOrderManagementDispatchRoute: typeof MainOrdersOrderManagementDispatchRoute
  MainOrdersOrderManagementFinalFeedbackRoute: typeof MainOrdersOrderManagementFinalFeedbackRoute
  MainOrdersOrderManagementLinkRoute: typeof MainOrdersOrderManagementLinkRoute
  MainOrdersOrderManagementReceivingBrovaFinalRoute: typeof MainOrdersOrderManagementReceivingBrovaFinalRoute
  MainOrdersOrderManagementUnlinkRoute: typeof MainOrdersOrderManagementUnlinkRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainOrdersCustomerProfilesOrdersRoute: MainOrdersCustomerProfilesOrdersRoute,
  MainOrdersNewAlterationOrderRoute: MainOrdersNewAlterationOrderRoute,
  MainOrdersNewSalesOrderRoute: MainOrdersNewSalesOrderRoute,
  MainOrdersNewWorkOrderRoute: MainOrdersNewWorkOrderRoute,
  MainOrdersOrdersAtShowroomRoute: MainOrdersOrdersAtShowroomRoute,
  MainStoreEndOfDayReportRoute: MainStoreEndOfDayReportRoute,
  MainStoreReceivingDeliveriesRoute: MainStoreReceivingDeliveriesRoute,
  MainStoreRequestDeliveryRoute: MainStoreRequestDeliveryRoute,
  MainStoreStockReportRoute: MainStoreStockReportRoute,
  MainOrdersOrderManagementAlterationsRoute:
    MainOrdersOrderManagementAlterationsRoute,
  MainOrdersOrderManagementBrovaFeedbackRoute:
    MainOrdersOrderManagementBrovaFeedbackRoute,
  MainOrdersOrderManagementCancelOrderRoute:
    MainOrdersOrderManagementCancelOrderRoute,
  MainOrdersOrderManagementChangeOptionsRoute:
    MainOrdersOrderManagementChangeOptionsRoute,
  MainOrdersOrderManagementDispatchRoute:
    MainOrdersOrderManagementDispatchRoute,
  MainOrdersOrderManagementFinalFeedbackRoute:
    MainOrdersOrderManagementFinalFeedbackRoute,
  MainOrdersOrderManagementLinkRoute: MainOrdersOrderManagementLinkRoute,
  MainOrdersOrderManagementReceivingBrovaFinalRoute:
    MainOrdersOrderManagementReceivingBrovaFinalRoute,
  MainOrdersOrderManagementUnlinkRoute: MainOrdersOrderManagementUnlinkRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRouteRoute: MainRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  HomeRoute: HomeRoute,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
